Autodock
IntelLabs/Open-Omics-Acceleration-Framework pull request #14
Opened 2024-10-30 13:30 UTC by sri480673

2024-11-05 03:00 UTC, manasi-t24 requested changes

2024-11-05 03:09 UTC, sri480673 commented on applications/Autodock/data_download_script.sh
ok manasi. Thanks for your suggestion

2024-11-05 03:27 UTC, manasi-t24 requested changes

2024-11-05 03:27 UTC, manasi-t24 commented on applications/Autodock/README.md
We need to update README so that it doesn't contain TransOmics.OpenOmicsInternal.git.

2024-11-08 04:50 UTC, manasi-t24 approved these changes

2024-11-08 04:51 UTC, manasi-t24 approved these changes

2024-11-08 05:11 UTC, sri480673 commented on applications/Autodock/README.md
README has been updated on above changes

2024-11-08 05:19 UTC, manasi-t24 approved these changes

2024-11-18 15:43 UTC, merged