Autodock vina
IntelLabs/Open-Omics-Acceleration-Framework pull request #15
Opened 2024-10-30 16:36 UTC by sri480673

2024-11-05 03:26 UTC, manasi-t24 requested changes

2024-11-05 03:26 UTC, manasi-t24 commented on applications/AutoDock-Vina/data_download_script.sh
Same comment about letting the downloaded dataset remain.

2024-11-05 03:26 UTC, manasi-t24 commented on applications/AutoDock-Vina/README.md
We need to update README so that it doesn't contain TransOmics.OpenOmicsInternal.git.

2024-11-08 05:09 UTC, sri480673 commented on applications/AutoDock-Vina/README.md
Done this update

2024-11-08 05:20 UTC, manasi-t24 approved these changes

2024-11-18 15:41 UTC, manasi-t24 approved these changes

2024-11-18 15:46 UTC, merged